const products = [
    {
        image:  "./src/assets/acaraje.webp",
        title: "Acarajé",
        description: "Feijão-fradinho frito em azeite de dendê.",
        price: "R$ 13,90",
        type: "dishes",
    },
    {
        image:  "./src/assets/brigadeiro.webp",
        title: "Brigadeiro",
        description: "Leite condensado e chocolate.",
        price: "R$ 5,90",
        type: "dessert",
    },
    {
        image:  "./src/assets/pizza.jpg",
        title: "Pizza de Frango com Catupiry",
        description: "Frango desfiado, milho e catupiry",
        price: "R$ 43,90",
        type: "dishes",
    },
    {
        image:  "./src/assets/vatapa.jpg",
        title: "Vatapá",
        description: "Pão molhado e farinha de rosca",
        price: "R$ 13,90",
        type: "dishes",
    },
    {
        image:  "./src/assets/mugunza.jpeg",
        title: "Mugunzá",
        description: "Milho-branco,leite, açúcar e canela em pó.",
        price: "R$ 14,90",
        type: "dessert",
    },
    {
        image:  "./src/assets/acai.jpeg",
        title: "Açaí",
        description: "Fruto bacáceo de cor roxa.",
        price: "R$ 22,90",
        type: "dessert",
    },
    {
        image:  "./src/assets/frango_yin_yang.png",
        title: "Frango Yin Yang",
        description: "Um pouco de batata, um pouco de salada",
        price: "R$ 13,90",
        type: "dishes",
    },
    {
        image:  "./src/assets/milkshake.jpeg",
        title: "MilkShake",
        description: "Copo 700ml",
        price: "R$ 24,90",
        type: "drink",
    },
    {
        image:  "./src/assets/suco-de-laranja-orig-1.jpg",
        title: "Suco de laranja",
        description: "Copo 500 ml",
        price: "R$ 8,00",
        type: "drink",
    },
    {
        image:  "./src/assets/coquinha_gelada.png",
        title: "Coquinha gelada",
        description: "Lata 350ml",
        price: "R$ 4,90",
        type: "drink",
    },
    {
        image:  "./src/assets/pudim.png",
        title: "Pudim",
        description: "Apenas pudim",
        price: "R$ 7,90",
        type: "dessert",
    },
    {
        image:  "./src/assets/marguerita.jpg",
        title: "Pizza de Marguerita",
        description: "Muçarela, tomate e manjericão.",
        price: "R$ 31,99",
        type: "dishes",
    },
    {
        image:  "./src/assets/pizza-de-romeu-e-julieta.webp",
        title: "Pizza de Romeu e Julieta",
        description: "Queijo muçarela e doce de goiabada.",
        price: "R$ 31,99",
        type: "dessert",
    },
    {
        image:  "./src/assets/pizza-de-calabresa.jpg",
        title: "Pizza de Calabresa",
        description: "Queijo muçarela, tomate, calabresa.",
        price: "R$ 31,99",
        type: "dishes",
    },
    {
        image:  "./src/assets/pave-de-chocolate.webp",
        title: "Pavê de chocolate ",
        description: "Biscoito, chocolate e leite condensado.",
        price: "R$ 31,99",
        type: "dessert",
    },
    {
        image:  "./src/assets/limao.jpeg",
        title: "Suco de limão",
        description: "550ml",
        price: "R$ 10,50",
        type: "drink",
    },
    {
        image:  "./src/assets/refri-pepsi.jpeg",
        title: "Pepsi gelada",
        description: "Lata 350ml",
        price: "R$ 4,99",
        type: "drink",
    },
    {
        image:  "./src/assets/sprite.jpg",
        title: "Sprite gelada",
        description: "Lata 350ml",
        price: "R$ 4,99",
        type: "drink",
    },
    {
        image:  "./src/assets/acaraje.webp",
        title: "Acarajé",
        description: "Feijão-fradinho frito em azeite de dendê.",
        price: "R$ 13,90",
        type: "dishes",
    },
    {
        image:  "./src/assets/brigadeiro.webp",
        title: "Brigadeiro",
        description: "Leite condensado e chocolate.",
        price: "R$ 5,90",
        type: "dessert",
    },
    {
        image:  "./src/assets/pizza.jpg",
        title: "Pizza de Frango com Catupiry",
        description: "Frango desfiado, milho e catupiry",
        price: "R$ 43,90",
        type: "dishes",
    },
    {
        image:  "./src/assets/vatapa.jpg",
        title: "Vatapá",
        description: "Pão molhado e farinha de rosca",
        price: "R$ 13,90",
        type: "dishes",
    },
    {
        image:  "./src/assets/mugunza.jpeg",
        title: "Mugunzá",
        description: "Milho-branco,leite, açúcar e canela em pó.",
        price: "R$ 14,90",
        type: "dessert",
    },
    {
        image:  "./src/assets/acai.jpeg",
        title: "Açaí",
        description: "Fruto bacáceo de cor roxa.",
        price: "R$ 22,90",
        type: "dessert",
    },
    {
        image:  "./src/assets/frango_yin_yang.png",
        title: "Frango Yin Yang",
        description: "Um pouco de batata, um pouco de salada",
        price: "R$ 13,90",
        type: "dishes",
    },
    {
        image:  "./src/assets/milkshake.jpeg",
        title: "MilkShake",
        description: "Copo 700ml",
        price: "R$ 24,90",
        type: "drink",
    },
    {
        image:  "./src/assets/suco-de-laranja-orig-1.jpg",
        title: "Suco de laranja",
        description: "Copo 500 ml",
        price: "R$ 8,00",
        type: "drink",
    },
    {
        image:  "./src/assets/coquinha_gelada.png",
        title: "Coquinha gelada",
        description: "Lata 350ml",
        price: "R$ 4,90",
        type: "drink",
    },
    {
        image:  "./src/assets/pudim.png",
        title: "Pudim",
        description: "Apenas pudim",
        price: "R$ 7,90",
        type: "dessert",
    },
    {
        image:  "./src/assets/marguerita.jpg",
        title: "Pizza de Marguerita",
        description: "Muçarela, tomate e manjericão.",
        price: "R$ 31,99",
        type: "dishes",
    },
    {
        image:  "./src/assets/pizza-de-romeu-e-julieta.webp",
        title: "Pizza de Romeu e Julieta",
        description: "Queijo muçarela e doce de goiabada.",
        price: "R$ 31,99",
        type: "dessert",
    },
    {
        image:  "./src/assets/pizza-de-calabresa.jpg",
        title: "Pizza de Calabresa",
        description: "Queijo muçarela, tomate, calabresa.",
        price: "R$ 31,99",
        type: "dishes",
    },
    {
        image:  "./src/assets/pave-de-chocolate.webp",
        title: "Pavê de chocolate ",
        description: "Biscoito, chocolate e leite condensado.",
        price: "R$ 31,99",
        type: "dessert",
    },
    {
        image:  "./src/assets/limao.jpeg",
        title: "Suco de limão",
        description: "550ml",
        price: "R$ 10,50",
        type: "drink",
    },
    {
        image:  "./src/assets/refri-pepsi.jpeg",
        title: "Pepsi gelada",
        description: "Lata 350ml",
        price: "R$ 4,99",
        type: "drink",
    },
    {
        image:  "./src/assets/sprite.jpg",
        title: "Sprite gelada",
        description: "Lata 350ml",
        price: "R$ 4,99",
        type: "drink",
    },
    {
        image:  "./src/assets/acaraje.webp",
        title: "Acarajé",
        description: "Feijão-fradinho frito em azeite de dendê.",
        price: "R$ 13,90",
        type: "dishes",
    },
    {
        image:  "./src/assets/brigadeiro.webp",
        title: "Brigadeiro",
        description: "Leite condensado e chocolate.",
        price: "R$ 5,90",
        type: "dessert",
    },
    {
        image:  "./src/assets/pizza.jpg",
        title: "Pizza de Frango com Catupiry",
        description: "Frango desfiado, milho e catupiry",
        price: "R$ 43,90",
        type: "dishes",
    },
    {
        image:  "./src/assets/vatapa.jpg",
        title: "Vatapá",
        description: "Pão molhado e farinha de rosca",
        price: "R$ 13,90",
        type: "dishes",
    },
    {
        image:  "./src/assets/mugunza.jpeg",
        title: "Mugunzá",
        description: "Milho-branco,leite, açúcar e canela em pó.",
        price: "R$ 14,90",
        type: "dessert",
    },
    {
        image:  "./src/assets/acai.jpeg",
        title: "Açaí",
        description: "Fruto bacáceo de cor roxa.",
        price: "R$ 22,90",
        type: "dessert",
    },
    {
        image:  "./src/assets/frango_yin_yang.png",
        title: "Frango Yin Yang",
        description: "Um pouco de batata, um pouco de salada",
        price: "R$ 13,90",
        type: "dishes",
    },
    {
        image:  "./src/assets/milkshake.jpeg",
        title: "MilkShake",
        description: "Copo 700ml",
        price: "R$ 24,90",
        type: "drink",
    },
    {
        image:  "./src/assets/suco-de-laranja-orig-1.jpg",
        title: "Suco de laranja",
        description: "Copo 500 ml",
        price: "R$ 8,00",
        type: "drink",
    },
    {
        image:  "./src/assets/coquinha_gelada.png",
        title: "Coquinha gelada",
        description: "Lata 350ml",
        price: "R$ 4,90",
        type: "drink",
    },
    {
        image:  "./src/assets/pudim.png",
        title: "Pudim",
        description: "Apenas pudim",
        price: "R$ 7,90",
        type: "dessert",
    },
    {
        image:  "./src/assets/marguerita.jpg",
        title: "Pizza de Marguerita",
        description: "Muçarela, tomate e manjericão.",
        price: "R$ 31,99",
        type: "dishes",
    },
    {
        image:  "./src/assets/pizza-de-romeu-e-julieta.webp",
        title: "Pizza de Romeu e Julieta",
        description: "Queijo muçarela e doce de goiabada.",
        price: "R$ 31,99",
        type: "dessert",
    },
    {
        image:  "./src/assets/pizza-de-calabresa.jpg",
        title: "Pizza de Calabresa",
        description: "Queijo muçarela, tomate, calabresa.",
        price: "R$ 31,99",
        type: "dishes",
    },
    {
        image:  "./src/assets/pave-de-chocolate.webp",
        title: "Pavê de chocolate ",
        description: "Biscoito, chocolate e leite condensado.",
        price: "R$ 31,99",
        type: "dessert",
    },
    {
        image:  "./src/assets/limao.jpeg",
        title: "Suco de limão",
        description: "550ml",
        price: "R$ 10,50",
        type: "drink",
    },
    {
        image:  "./src/assets/refri-pepsi.jpeg",
        title: "Pepsi gelada",
        description: "Lata 350ml",
        price: "R$ 4,99",
        type: "drink",
    },
    {
        image:  "./src/assets/sprite.jpg",
        title: "Sprite gelada",
        description: "Lata 350ml",
        price: "R$ 4,99",
        type: "drink",
    },
]




       
    
